services:

  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./photos:/photos

  db:
    image: postgres:17
    environment:
      POSTGRES_USER: photos
      POSTGRES_PASSWORD: photos
      POSTGRES_DB: photos